// Bot decision logic: weighted-random-but-valid. Every function here is
// pure - it only ever reads its arguments and GAME_BALANCE, never touches
// room/match state directly - so match.js's resolveBotTurn (which already
// has the live player objects and freshly generated offer pools) is the
// only caller, and this stays trivially fuzz-testable headlessly.

import { GAME_BALANCE } from './balance.js';
import { randomChoice } from './utils.js';
import { RANKS, getNextRank } from './player.js';
import { validatePolitik } from './politics.js';
import { validateSabotaj } from './sabotage.js';
import { validateMedia } from './media.js';
import { validateRaid, validateMarketPurchase } from './politicalOpportunities.js';

const { bots: cfg } = GAME_BALANCE;

function weightedPick(items) {
  const total = items.reduce((sum, item) => sum + item.weight, 0);
  if (total <= 0) return items[0] || null;
  let roll = Math.random() * total;
  for (const item of items) {
    roll -= item.weight;
    if (roll <= 0) return item;
  }
  return items[items.length - 1];
}

// Kabel targets anyone ranked above; a normal Sabotaj only ever targets the
// (necessarily full) seat directly above - same restriction validateSabotaj
// itself enforces, just pre-filtered here so weightedPick never sees an
// invalid target.
function pickSabotajTarget(bot, players) {
  if (bot.hasKabel) {
    const candidates = players.filter((p) => p.id !== bot.id && RANKS.indexOf(p.rank) > RANKS.indexOf(bot.rank));
    const valid = candidates.filter((t) => validateSabotaj(bot, t, players, 0, { isKabel: true }).ok);
    return valid.length ? randomChoice(valid) : null;
  }
  const toRank = getNextRank(bot.rank);
  if (!toRank) return null;
  const candidates = players.filter((p) => p.id !== bot.id && p.rank === toRank);
  const valid = candidates.filter((t) => validateSabotaj(bot, t, players, 0).ok);
  return valid.length ? randomChoice(valid) : null;
}

// Biases toward whichever rival's asset is easiest to profitably hit by
// weighting every (target, asset) pair equally and letting a rival who
// simply owns more assets come up more often - the juiciest targets to
// raid are the ones already sitting on the most.
function pickRaidTarget(bot, players) {
  const options = [];
  players
    .filter((p) => p.id !== bot.id && p.assets.length > 0)
    .forEach((target) => {
      target.assets.forEach((asset) => {
        if (validateRaid(bot, target, asset.id, 0).ok) options.push({ target, asset, weight: 1 });
      });
    });
  return options.length ? weightedPick(options) : null;
}

// Returns exactly one turn action to take, never null - Projek has no
// failure condition beyond needing an offer (always true, PROJECT_CARDS is
// never empty), so it's always in the candidate pool as a guaranteed
// fallback. `offers` is { projekOffers, mediaOffers, marketOffers } -
// generated by the caller via the same generate*Offers() functions the UI
// itself uses, kept out of this module to keep it a pure function of its
// arguments.
export function decideBotAction(bot, players, offers) {
  const w = cfg.actionWeights;
  const candidates = [
    { type: 'projek', weight: w.projek, build: () => ({ type: 'projek', cardId: randomChoice(offers.projekOffers).id }) },
  ];

  if (validatePolitik(bot, players, 0).ok) {
    candidates.push({ type: 'politik', weight: w.politik, build: () => ({ type: 'politik', extraInfluence: 0 }) });
  }

  const sabotajTarget = pickSabotajTarget(bot, players);
  if (sabotajTarget) {
    candidates.push({ type: 'sabotaj', weight: w.sabotaj, build: () => ({ type: 'sabotaj', targetId: sabotajTarget.id, extraInfluence: 0 }) });
  }

  const mediaTarget = randomChoice(players.filter((p) => p.id !== bot.id)) || null;
  const validMediaCards = offers.mediaOffers.filter((card) => validateMedia(bot, card.id, mediaTarget).ok);
  if (validMediaCards.length) {
    candidates.push({
      type: 'media',
      weight: w.media,
      build: () => {
        const card = randomChoice(validMediaCards);
        return { type: 'media', cardId: card.id, targetId: card.kind === 'target' ? mediaTarget.id : undefined };
      },
    });
  }

  const raidPick = pickRaidTarget(bot, players);
  if (raidPick) {
    candidates.push({ type: 'raid', weight: w.raid, build: () => ({ type: 'raid', targetId: raidPick.target.id, assetId: raidPick.asset.id, extraInfluence: 0 }) });
  }

  const affordableMarketTypes = offers.marketOffers.filter((type) => validateMarketPurchase(bot, type).ok);
  if (affordableMarketTypes.length) {
    candidates.push({ type: 'market', weight: w.market, build: () => ({ type: 'market', assetType: randomChoice(affordableMarketTypes) }) });
  }

  return weightedPick(candidates).build();
}

// null when the roll misses, no rival exists, or the bot has nothing it
// can spare - resolveBotTurn treats null as "don't propose this turn".
export function decideDealProposal(bot, players) {
  if (Math.random() * 100 >= cfg.actionWeights.dealPropose) return null;

  const rivals = players.filter((p) => p.id !== bot.id);
  if (!rivals.length) return null;

  const distance = (p) => Math.abs(RANKS.indexOf(p.rank) - RANKS.indexOf(bot.rank));
  const minDistance = Math.min(...rivals.map(distance));
  const target = randomChoice(rivals.filter((p) => distance(p) === minDistance));

  const money = Math.floor((bot.money * cfg.dealOfferPercent) / 100);
  const influence = Math.floor((bot.influence * cfg.dealOfferPercent) / 100);
  if (money <= 0 && influence <= 0) return null;

  return { targetId: target.id, money, influence };
}

// A clean deal never hurts the recipient, so a bot gets more willing to
// accept as its own Scandal climbs - it has nothing left to protect.
export function decideDealResponse(bot, offer) {
  const total = (offer.money || 0) + (offer.influence || 0);
  const threshold = cfg.dealAcceptMinValue * (1 - Math.min(bot.scandal, 100) / 200);
  return total >= threshold;
}
